api_version = "2024-04"

[[extensions]]
name = "Bike Reservation Widget"
handle = "bike-reservation-widget"
type = "theme"

  [[extensions.blocks]]
  template = "blocks/reservation-button.liquid"
  name = "Reserve Bike Button"
  target = "section"

  [extensions.blocks.presets]
  name = "Bike Reservation Button"

  [[extensions.blocks]]
  template = "blocks/reservation-page.liquid"
  name = "Reservation Page"
  target = "section"

  [extensions.blocks.presets]
  name = "Bike Reservation Page"

  [[extensions.blocks]]
  template = "blocks/reservation-general.liquid"
  name = "Reserve Any Bike"
  target = "section"

  [extensions.blocks.presets]
  name = "Reserve Any Bike Button"
